.ORIG x3000

;;YOUR CODE STARTS HERE
BIGLOOP

	LD R6,STRING_START
	LDR R0,R6,#0
	LD R5,ASCII_NINE
	NOT R5,R5
	ADD R5,R5,#1	;NEG_NINE
	ADD R4,R5,R0
	BRp JUSTOUT


	LD R5,ASCII_NEG_ASTERISK
	ADD R5,R5,R0
	BRz 

	ADD R6,R6,#1

JUSTOUT
	OUT
	ADD R6,R6,#1
	BRnzp BIGLOOP

ASCII_ZERO		.FILL x0030		;ASCII value of Zero
ASCII_NINE		.FILL x0039		;ASCII value of Nine
ASCII_NEG_ASTERISK   	.FILL xFFD6  		;negative of ascii value of *
ASCII_NEG_ZERO    	.FILL xFFD0		;negative of ascii value of 0
STRING_START 		.FILL x4000		;starting address of string
.END
